//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyManagment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int Id { get; set; }
        public string PropertyNumber { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string Badroom { get; set; }
        public string Bathroom { get; set; }
        public string Kitchen { get; set; }
        public string Parking { get; set; }
        public string Size { get; set; }
        public string Type { get; set; }
        public string Livingroom { get; set; }
        public string Status { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ClientId { get; set; }
        public string ImagePath { get; set; }
    
        public virtual User User { get; set; }
    }
}
